version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret
      - WEATHER_API_KEY=your_openweathermap_api_key